server:
  port: 8080
  servlet:
    context-path: /community

spring:
  # 将application-local.yml包进来
  profiles:
    active: local
    include: -local

  thymeleaf:
    cache: true
    check-template: true
    encoding: utf-8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 3000

  mail:
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  redis:
    database: 11
    host: localhost
    port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: community-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000

  elasticsearch:
    uris: http://localhost:9200

  task:
    # 线程池配置
    execution:
      pool:
        core-size: 5
        max-size: 15
        queue-capacity: 100
    # 定时器配置
    scheduling:
      pool:
        size: 5

  quartz:
    job-store-type: jdbc
    scheduler-name: communityScheduler
    # 未解析？
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            # 2.5.6的版本后class将不再支持原方案进行配置默认数据源，需改为如下配置
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.hhy.communitysystem.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

community:
  path:
    domain: http://localhost:8080
    # 需要修改为本机的绝对路径
    upload: /Users/hhy/JavaProjects/community-system/header_upload

caffeine:
  posts:
    max-size: 15
    expire-seconds: 180

